@startuml
Perso "1" <|-- "*"Labyrinthe : +pj

Perso : +x
Perso : +y
Perso : +Perso()
Perso : +etrePresent(int dx, int dy): boolean
Perso : +getX()
Perso : +getY()

Labyrinthe : +murs
Labyrinthe : Static getsuivant(int x, int y, String action):int 
Labyrinthe : +Labyrinthe(String nom)
Labyrinthe : +deplacerPerso(String action): void
Labyrinthe : +etreFini(): boolean
Labyrinthe : +getLengthY(): int
Labyrinthe : +getLength(): int
Labyrinthe : +getMur(int x,int y): boolean
@enduml


