@startuml
title Diagramme de séquence - Considérer le monstre dans les déplacements du personnage

participant "laby : Labyrinthe" as laby
participant "pj : Perso" as perso
participant "monstre : Monstre" as monstre

-> laby : deplacerPerso(action)
activate laby

laby -> perso : getX()
activate perso
perso --> laby : pj.x
laby -> perso : getY()
perso --> laby : pj.y
deactivate perso

laby -> laby : getSuivant(pj.x, pj.y, action)
laby --> laby : int[] suivante {xSuiv, ySuiv}

laby -> laby : murs[xSuiv][ySuiv]
laby --> laby : boolean estMur

laby -> laby : estCaseOccupeeParMonstre(xSuiv, ySuiv)
activate laby

alt foreach monstre in monstres
    laby -> monstre : estmort()
    activate monstre
    monstre --> laby : boolean
    alt monstre non mort
        laby -> monstre : getX()
        monstre --> laby : monstre.x
        laby -> monstre : getY()
        monstre --> laby : monstre.y
    end
    deactivate monstre
end
laby --> laby : boolean caseOccupee

deactivate laby

alt case libre (pas mur et pas occupée par monstre)
    laby -> perso : pj.x = xSuiv
    laby -> perso : pj.y = ySuiv
end

<-- laby
deactivate laby
@enduml
